### ISSUE TITLE
Initial public release checklist

### ISSUE THREAD

**Issue by epicallan** [epicallan/hreq#1]
- [x] Support type-level specification of request params
- [x] Possibly add more type combinators to make type specifications shorter
- [x] ~Throw error on incorrect status~
- [x] Add HTTP headers support
- [x] ~make Get requests with ReqBody invalid, this is not strictly part of the HTTP spec~
- [x] ~Don't use Hlist for single "request query item" Apis~ not worth the effort
- [x] Implement the `HTTP.Response -> Response` function
- [x] Add content-type and Accept Header for each request (sort of complete)
- [x] Auth and Cookie support
- [x] Add tests and ensure all valid API descriptions work fine.
- [x] support GHC 8.2, 8.4 and 8.8. Currently only working with 8.6.5
- [x] Consider Content-type header before decoding response body 
- [x] Make API better and more similar to servant client API by getting rid of type-level list requirement for request and response components.
- [x] support streaming (implemented foundation work, still not done completely)
- [x] Add more docs
- [x] re-look at build dependencies version boundaries
- [x] buildable readme file
- [x] Turn into a mono-repo with distinct packages
- [x] Replace Http references to Client with in Hreq-core
- [x] Streaming support
- [x] In-built retry mechanism
- [x] optimise and benchmark (not fully done)
- [x] Add working blog link to read-me file
- [x] tutorial / introductory article

- [x] Upload to Hackage and Stackage
