### ISSUE TITLE
Next release checklist

### ISSUE THREAD

**Issue by epicallan** [epicallan/hreq#17]
- [ ] Better streaming support
- [ ] Turn into a mono-repo with distinct packages
- [x] code doc-tests
